version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    network_mode: host
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    container_name: honeypot-backend
    image: ghcr.io/frnkst/honeypot-backend:latest
    network_mode: host
    env_file:
      - .env
    depends_on:
      - db
  ui:
    container_name: honeypot-frontend
    image: ghcr.io/frnkst/honeypot-frontend:latest
    network_mode: host
  ssh-honeypot:
    container_name: ssh-honeypot
    image: ghcr.io/frnkst/ssh-honeypot:latest
    network_mode: host
    restart: always
    env_file:
      - .env
    depends_on:
      - db
