version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_database_and_table.sql
  api:
    container_name: honeypot-backend:latest
    image: ghcr.io/frnkst/honeypot-backend
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: honeypot
    links:
      - db
    volumes:
      - './:/src'
  ui:
    container_name: honeypot-frontend
    image: ghcr.io/frnkst/honeypot-frontend
volumes:
  db:
    driver: local
