name: backend build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install
        run: npm install

      - name: artifact id
        if: github.ref == 'refs/heads/main'
        run: echo "ARTIFACT_ID=$(date +%Y-%m-%dT%H-%M)_$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: login to container registry
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: docker build and publish
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./backend/Dockerfile
          push: true
          tags: ghcr.io/${{ github.actor }}/honeypot-backend:${{ env.ARTIFACT_ID }}
